name: Android Build
concurrency: android
on:
  push:
    branches: [master]
    paths:
      - android/**
      - lib/**
      - assets/**
      - pubspec.yaml
      - pubspec.lock
  workflow_dispatch:
    inputs:
      changesNotSentForReview:
        description: "Don't Send for review"
        required: false
        type: boolean
        default: false

env:
  WEBSITE_URL: https://revelationsai.com
  AUTH_URL: https://auth.revelationsai.com
  API_URL: https://api.revelationsai.com
  CHAT_API_URL: https://chat.api.revelationsai.com

  REVENUECAT_PLAY_STORE_API_KEY: ${{ secrets.REVENUECAT_PLAY_STORE_API_KEY }}

  NEW_RELIC_ANDROID_APP_TOKEN: ${{ secrets.NEW_RELIC_ANDROID_APP_TOKEN }}

  ENCODED_ANDROID_KEYSTORE: ${{ secrets.ENCODED_ANDROID_KEYSTORE }}
  ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}

jobs:
  build_android:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "11"
      - id: setup_flutter
        name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: install_dependencies
        name: Install dependencies
        run: flutter pub get
      - id: generate_code
        name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
      - id: generate_keystore
        name: Generate Keystore
        run: |
          echo $ENCODED_ANDROID_KEYSTORE | base64 --decode > android/app/keystore.jks
      - id: generate_keystore_properties
        name: Generate Keystore Properties
        run: |
          echo "storePassword=$ANDROID_STORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$ANDROID_KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$ANDROID_KEY_ALIAS" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
      - name: Set Flutter Version Code
        env:
          RUN_NUM: ${{ github.run_number }}
        run: |
          echo ::set-env name=FLUTTER_VERSION_CODE::$(($RUN_NUM+132))
          echo $FLUTTER_VERSION_CODE
      - id: build_appbundle
        name: Build App Bundle for Android
        run: |
          flutter build appbundle --release --obfuscate \
            --split-debug-info=build/android/debug-info \
            --dart-define WEBSITE_URL=$WEBSITE_URL \
            --dart-define AUTH_URL=$AUTH_URL \
            --dart-define API_URL=$API_URL \
            --dart-define CHAT_API_URL=$CHAT_API_URL \
            --dart-define REVENUECAT_PLAY_STORE_API_KEY=$REVENUECAT_PLAY_STORE_API_KEY \
            --dart-define NEW_RELIC_ANDROID_APP_TOKEN=$NEW_RELIC_ANDROID_APP_TOKEN
      - name: Archive Obfuscation Mapping
        uses: actions/upload-artifact@v2
        with:
          name: android-obfuscation-mapping
          path: build/android/debug-info/*.symbols
      - name: Create google cloud service account key file
        run: echo ${{ secrets.ENCODED_GOOGLE_CLOUD_SVC_ACCOUNT_JSON }} | base64 --decode > google-cloud-key.json
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: google-cloud-key.json
          packageName: com.passgoco.revelationsai
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: production
          changesNotSentForReview: ${{ inputs.changesNotSentForReview }}
